# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'

  # Pods for PhotoApp

  target 'PhotoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoAppUITests' do
    inherit! :search_paths
    pod 'Kingfisher'
  end

end
